params:
  experiment: "self_attn_agent_v3"

  paths:
    trained_weigths_path:
    trained_model_path_to_train:
    trained_model_path_to_test: "./weights/"
    weigths_path_to_save: "./weights/"
    test_trained_videos_path: "./videos/trained/"
    test_stupid_videos_path: "./videos/stupid/"
    figures_path: "./figures/"

  common:
    env_name: "KungFuMasterDeterministic-v0"
    height: 42
    width: 42

  model:
    hidden_dim: 256
    conv_filters_num: 64
    linear_dim: 256

  train:
    parallels_game_count: 5
    iter_count: 15000
    reward_limit: 10000
    lr: 0.0001
    gamma: 0.99

  test:
    game_count: 2